addSbtPlugin("org.scalameta"             % "sbt-scalafmt" % "2.5.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.4.2")
addSbtPlugin("com.github.sbt"            % "sbt-dynver"   % "5.0.1")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype" % "3.11.0")
addSbtPlugin("com.github.sbt"            % "sbt-pgp"      % "2.2.1")
