addSbtPlugin("org.scalameta"  % "sbt-scalafmt" % "2.5.2")
addSbtPlugin("org.typelevel"  % "sbt-tpolecat" % "0.5.2")
addSbtPlugin("com.github.sbt" % "sbt-dynver"   % "5.0.1")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.11.2")
addSbtPlugin("com.github.sbt" % "sbt-pgp"      % "2.3.0")
